import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignInButton, SignedIn, SignedOut } from "@clerk/nextjs";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center bg-slate-900 text-white">
        <div className="container mt-12 flex flex-col items-center justify-center gap-4 px-4 py-8">
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            tra<span className="text-pink-400">ai</span>n
          </h1>
        </div>
        <SignedIn>
          <Link href="/workouts">Workouts</Link>
          <Link href="/exercises">Exercises</Link>
          <Link href="/muscle-groups">Muscle Groups</Link>
        </SignedIn>
        <SignedOut>
          <SignInButton />
        </SignedOut>
      </main>
    </>
  );
};

export default Home;
